spring.application.name=iocexam

logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.springframework.web=DEBUG
logging.level.com.example=DEBUG

# 로그 파일 설정
logging.file.name=logs/application.log
logging.file.path=/var/logs
logging.file.max-size=10MB
logging.file.max-history=30

# 로그 패턴 설정
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# 로그 그룹 설정
logging.group.db=org.hibernate,org.springframework.jdbc
logging.level.db=DEBUG